env:
  - DOCKER_USERNAME=fengzhanyuan
sudo: required
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - ls
  - docker build -t landation/blog-ui:1.0.0 .
  - docker push landation/blog-ui:1.0.0